PATCH http://47.84.81.252:3001/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiZG5taW5oMjAwMyIsImlhdCI6MTcyNzY0NjMxMCwiZXhwIjoxNzI3NjQ5OTEwLCJhdWQiOiJteSIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.giyvVSUzwZQbP2_y6JWKVmobkE8_e6G_8J9VW3L_GxI

{
  "firstName": "John",
  "lastName": "Smith",
  "email": "john.smith@example.com",
  "age": 30
}

PATCH http://localhost:3000/users/1/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoidXNlcm5hbWUiLCJpYXQiOjE3MjczNTEwOTAsImV4cCI6MTcyNzM1NDY5MCwiYXVkIjoibXkiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.DvPJvJc0j5F0QUDn3cEwpcYX5c0x6DhLWkgO5hatilk

{
  "currentPassword": "Password@123",
  "newPassword": "Password@1234"
}